---
title: "CodeBook"
output: html_document
---

## Getting & Cleaning Data Course Project

### Source Data Links

A full description of the data used in this project can be found here:
[The UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones).
In addition, the source data for this project can be found here: [Human Activity Recognition Using Smartphones Dataset](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip).

### Further Data Set Information

The experiments have been carried out with a group of 30 volunteers within an age bracket of 19-48 years. Each person performed six activities (WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING) wearing a smartphone (Samsung Galaxy S II) on the waist. Using its embedded accelerometer and gyroscope, we captured 3-axial linear acceleration and 3-axial angular velocity at a constant rate of 50Hz. The experiments have been video-recorded to label the data manually. The obtained dataset has been randomly partitioned into two sets, where 70% of the volunteers was selected for generating the training data and 30% the test data. 

The sensor signals (accelerometer and gyroscope) were pre-processed by applying noise filters and then sampled in fixed-width sliding windows of 2.56 sec and 50% overlap (128 readings/window). The sensor acceleration signal, which has gravitational and body motion components, was separated using a Butterworth low-pass filter into body acceleration and gravity. The gravitational force is assumed to have only low frequency components, therefore a filter with 0.3 Hz cutoff frequency was used. From each window, a vector of features was obtained by calculating variables from the time and frequency domain. See 'features_info.txt' for more details. 

For each record it is provided:

- Triaxial acceleration from the accelerometer (total acceleration) and the estimated body acceleration.
- Triaxial Angular velocity from the gyroscope. 
- A 561-feature vector with time and frequency domain variables. 
- Its activity label. 
- An identifier of the subject who carried out the experiment.

### Variable - Feature Selection 

The features selected for this database come from the accelerometer and gyroscope 3-axial raw signals tAcc-XYZ and tGyro-XYZ. These time domain signals (prefix 't' to denote time) were captured at a constant rate of 50 Hz. Then they were filtered using a median filter and a 3rd order low pass Butterworth filter with a corner frequency of 20 Hz to remove noise. Similarly, the acceleration signal was then separated into body and gravity acceleration signals (tBodyAcc-XYZ and tGravityAcc-XYZ) using another low pass Butterworth filter with a corner frequency of 0.3 Hz. 

Subsequently, the body linear acceleration and angular velocity were derived in time to obtain Jerk signals (tBodyAccJerk-XYZ and tBodyGyroJerk-XYZ). Also the magnitude of these three-dimensional signals were calculated using the Euclidean norm (tBodyAccMag, tGravityAccMag, tBodyAccJerkMag, tBodyGyroMag, tBodyGyroJerkMag). 

Finally a Fast Fourier Transform (FFT) was applied to some of these signals producing fBodyAcc-XYZ, fBodyAccJerk-XYZ, fBodyGyro-XYZ, fBodyAccJerkMag, fBodyGyroMag, fBodyGyroJerkMag. (Note the 'f' to indicate frequency domain signals). 

These signals were used to estimate variables of the feature vector for each pattern:  
'-XYZ' is used to denote 3-axial signals in the X, Y and Z directions.

The set of variables that were estimated from these signals & used in this analysis are: 
mean(): Mean value
std(): Standard deviation

### Variable Detail

 #  | Variable Name      				| Variable Type 		     | Variable Values	               | Variable Description	
----|:------------------------------------------|:---------------------------|:--------------------------------|:----------------------------------------------|
|1  |Subject                                    | Integer           	  	 | 1 - 30			   | Each row identifies the subject who performed the activity for each window sample. Its range is from 1 to 30.|
|2  |Activity                                   | Factor w/ 6 levels         | WALKING, WALKING_UPSTAIRS, WALKING_DOWNSTAIRS, SITTING, STANDING, LAYING | Activity being performed by subject.
|3  |timeBodyAccelerometerMeanX                 | Numeric       			| Features/Measures are normalized and bounded within [-1,1] | See above description of Feature/Measure variables. |
|4  |timeBodyAccelerometerMeanY                 | Numeric       			|
|5  |timeBodyAccelerometerMeanZ                 | Numeric       			|
|6  |timeBodyAccelerometerStdX                  | Numeric       			|
|7  |timeBodyAccelerometerStdY                  | Numeric       			|
|8  |timeBodyAccelerometerStdZ                  | Numeric       			|
|9  |timeGravityAccelerometerMeanX              | Numeric       			|
|10 |timeGravityAccelerometerMeanY              | Numeric       			|
|11 |timeGravityAccelerometerMeanZ              | Numeric       			|
|12 |timeGravityAccelerometerStdX               | Numeric       			|
|13 |timeGravityAccelerometerStdY               | Numeric       			|
|14 |timeGravityAccelerometerStdZ               | Numeric       			|
|15 |timeBodyAccelerometerJerkMeanX             | Numeric       			|
|16 |timeBodyAccelerometerJerkMeanY             | Numeric       			|
|17 |timeBodyAccelerometerJerkMeanZ             | Numeric       			|
|18 |timeBodyAccelerometerJerkStdX              | Numeric       			|
|19 |timeBodyAccelerometerJerkStdY              | Numeric       			|
|20 |timeBodyAccelerometerJerkStdZ              | Numeric       			|
|21 |timeBodyGyroscopeMeanX                     | Numeric       			|
|22 |timeBodyGyroscopeMeanY                     | Numeric       			|
|23 |timeBodyGyroscopeMeanZ                     | Numeric       			|
|24 |timeBodyGyroscopeStdX                      | Numeric       			|
|25 |timeBodyGyroscopeStdY                      | Numeric       			|
|26 |timeBodyGyroscopeStdZ                      | Numeric       			|
|27 |timeBodyGyroscopeJerkMeanX                 | Numeric       			|
|28 |timeBodyGyroscopeJerkMeanY                 | Numeric       			|
|29 |timeBodyGyroscopeJerkMeanZ                 | Numeric       			|
|30 |timeBodyGyroscopeJerkStdX                  | Numeric       			|
|31 |timeBodyGyroscopeJerkStdY                  | Numeric       			|
|32 |timeBodyGyroscopeJerkStdZ                  | Numeric       			|
|33 |timeBodyAccelerometerMagnitudeMean         | Numeric       			|
|34 |timeBodyAccelerometerMagnitudeStd          | Numeric       			|
|35 |timeGravityAccelerometerMagnitudeMean      | Numeric       			|
|36 |timeGravityAccelerometerMagnitudeStd       | Numeric       			|
|37 |timeBodyAccelerometerJerkMagnitudeMean     | Numeric       			|
|38 |timeBodyAccelerometerJerkMagnitudeStd      | Numeric       			|
|39 |timeBodyGyroscopeMagnitudeMean             | Numeric       			|
|40 |timeBodyGyroscopeMagnitudeStd              | Numeric       			|	
|41 |timeBodyGyroscopeJerkMagnitudeMean         | Numeric       			|
|42 |timeBodyGyroscopeJerkMagnitudeStd          | Numeric       			|
|43 |frequencyBodyAccelerometerMeanX            | Numeric       			|
|44 |frequencyBodyAccelerometerMeanY            | Numeric       			|
|45 |frequencyBodyAccelerometerMeanZ            | Numeric       			|
|46 |frequencyBodyAccelerometerStdX             | Numeric       			|
|47 |frequencyBodyAccelerometerStdY             | Numeric       			|
|48 |frequencyBodyAccelerometerStdZ             | Numeric       			|
|49 |frequencyBodyAccelerometerJerkMeanX        | Numeric       			|
|50 |frequencyBodyAccelerometerJerkMeanY        | Numeric       			|
|51 |frequencyBodyAccelerometerJerkMeanZ        | Numeric       			|
|52 |frequencyBodyAccelerometerJerkStdX         | Numeric       			|
|53 |frequencyBodyAccelerometerJerkStdY         | Numeric       			|
|54 |frequencyBodyAccelerometerJerkStdZ         | Numeric       			|
|55 |frequencyBodyGyroscopeMeanX                | Numeric       			|	
|56 |frequencyBodyGyroscopeMeanY                | Numeric       			|
|57 |frequencyBodyGyroscopeMeanZ                | Numeric       			|
|58 |frequencyBodyGyroscopeStdX                 | Numeric       			|
|59 |frequencyBodyGyroscopeStdY                 | Numeric       			|
|60 |frequencyBodyGyroscopeStdZ                 | Numeric       			|
|61 |frequencyBodyAccelerometerMagnitudeMean    | Numeric       			|
|62 |frequencyBodyAccelerometerMagnitudeStd     | Numeric 				|		      
|63 |frequencyBodyAccelerometerJerkMagnitudeMean| Numeric       			|
|64 |frequencyBodyAccelerometerJerkMagnitudeStd | Numeric       			|
|65 |frequencyBodyGyroscopeMagnitudeMean        | Numeric       			|
|66 |frequencyBodyGyroscopeMagnitudeStd         | Numeric       			|	
|67 |frequencyBodyGyroscopeJerkMagnitudeMean    | Numeric       			|
|68 |frequencyBodyGyroscopeJerkMagnitudeStd     | Numeric  				|


### Data Processing Transformations

The "tidydata.txt" summarizes the average measurements of the Human Activity Recognition Using Smartphones Dataset by Subject, Activity, Measurement.
The data was read directly into R, and then transformed from raw data into a wide-form, tidy summary data set.
The following transformations were perfomed on the original data:

1. Merges the training and the test sets to create one data set.
2. Extracts only the measurements on the mean and standard deviation for each measurement.
3. Uses descriptive activity names to name the activities in the data set
4. Appropriately labels the data set with descriptive variable names.
5. From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.

For further data cleanup details, please review:
[README](https://github.com/calypsorenee/____/README.md) and [run_analysis.R](https://github.com/calypsorenee/____/run_analysis.R).
